version: '3'
services:
    www:
        image: fholzer/nginx-brotli
        restart:
            always
        ports:
            - '8081:80'
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.wordpress.entrypoints=http'
            - 'traefik.http.routers.wordpress.rule=Host(`jamalu.de`)'
            - 'traefik.http.routers.wordpress.middlewares=https-redirect@file'
            - 'traefik.http.routers.wordpress-secure.entrypoints=https'
            - 'traefik.http.routers.wordpress-secure.rule=Host(`jamalu.de`)'
            - 'traefik.http.routers.wordpress-secure.tls=true'
            - 'traefik.http.routers.wordpress-secure.tls.certresolver=http'
            - 'traefik.http.routers.wordpress-secure.service=wordpress'
            - 'traefik.http.routers.wordpress-secure.middlewares=secHeaders@file'
            - 'traefik.http.services.wordpress.loadbalancer.server.port=80'
            - 'traefik.docker.network=proxy'
        volumes:
            - "./Output:/usr/share/nginx/html"
        networks:
            - proxy
networks:
    proxy:
        external: true
